chore!: migrate yaru.dart and yaru_icons.dart into yaru_widgets
ubuntu/yaru.dart pull request #836
Opened 2024-02-22 16:00 UTC by Feichtmeier

2024-02-23 13:41 UTC, Feichtmeier commented
https://github.com/ubuntu/yaru_widgets.dart/assets/15329494/a84e100d-5a88-4e96-9317-402a97c94439

The goldens pass locally after clean/upgrade and regeneration
So they will prbly need the nightly CI to pass again here, so you can ignore those failed golden tests

2024-02-24 09:22 UTC, Jupi007 requested changes
I think we can improve and simplify some files placements: 
- `colors.dart` could be moved to the `foundation/` folder ;
- `icons_foundation/` could be merged with `foundation` ;
- `text/font/` should be moved to `assets/`, and `text/text_theme.dart` to `themes/` ;
- `icons_widgets/` to `widgets` ;
- and I'm not sure, but `theme_widgets/inherited_theme.dart` can maybe be moved to `widgets/` (or `themes/`) ?

Except that, this looks great. I didn't noticed any problem with icons :D

2024-02-24 09:22 UTC, Jupi007 commented on pubspec.yaml
You forgotten to include the font files:

```
flutter:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-L.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu-LI.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Ubuntu-R.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu-RI.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Ubuntu-M.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-MI.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Ubuntu-B.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-BI.ttf
          weight: 700
          style: italic
`

2024-02-24 10:14 UTC, Feichtmeier commented on pubspec.yaml
Oh god 🙇 thanks

2024-02-24 10:19 UTC, Feichtmeier commented
> I think we can improve and simplify some files placements:
> 
>     * `colors.dart` could be moved to the `foundation/` folder ;
> 
>     * `icons_foundation/` could be merged with `foundation` ;
> 
>     * `text/font/` should be moved to `assets/`, and `text/text_theme.dart` to `themes/` ;
> 
>     * `icons_widgets/` to `widgets` ;
> 
>     * and I'm not sure, but `theme_widgets/inherited_theme.dart` can maybe be moved to `widgets/` (or `themes/`) ?
> 
> 
> Except that, this looks great. I didn't noticed any problem with icons :D

I kept the sup structure for this PR to make a first atempt where everything works. Maybe I could do this in a second PR? then I change from Fix to Ref in the PR desc
And thank you very much for catching the font!

2024-02-24 10:20 UTC, Jupi007 commented
> Maybe I could do this in a second PR?

Ofc, sounds good :+1:

2024-02-24 10:22 UTC, Jupi007 approved these changes
LGTM :+1:

2024-02-25 14:46 UTC, spydon approved these changes
Lgtm!

2024-02-25 14:46 UTC, spydon commented on README.md
> +- a theme for widgets from material.dart and from this repository here
This sentence reads a bit strange, maybe just remove "here"?

2024-02-25 14:59 UTC, merged